version: '3.8'

networks:
    budget:
      external: true

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5500:5500"
        volumes:
            - /app/node_modules
            - .:/app
        env_file: .env
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks: 
            - budget